steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-docker.pkg.dev/coffee-break-rob/coffee/hello-coffee:tag1', '.' ]
  images:
  - 'europe-docker.pkg.dev/coffee-break-rob/coffee/hello-coffee:tag1'