steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ["--destination=europe-docker.pkg.dev/secure-cicd-pipeline/hello-coffee/coffee", "--dockerfile=Dockerfile", "--cache=true", "--cache-ttl=24h"]    

timeout: '1600s'
