steps:
  - name: gcr.io/cloud-builders/docker
    id: Build Container Image
    args:
      - build
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE:$COMMIT_SHA'
      - .
  
  - name: gcr.io/cloud-builders/docker
    id: Push Container Image
    args:
      - push
      - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE:$COMMIT_SHA'
  
  - name: gcr.io/cloud-builders/gcloud
    id: Create a Cloud Deploy Candidate
    args:
      - deploy
      - releases
      - create
      - 'coffee-${SHORT_SHA}'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--delivery-pipeline'
      - '${_DEPLOY_PIPELINE}'
      - '--annotations'
      - 'commitID=${REVISION_ID}'
      - '--images'
      - 'app=$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY