apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
name: run-app-pipeline
description: application deployment pipeline
serialPipeline:
stages:
- targetId: dev-service
  profiles: [dev-service]
- targetId: prod-service
  profiles: [prod-service]
---


apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
name: dev-service
description: Cloud Run development service
run:
location: projects/secure-cicd-pipeline/locations/eu-west2
---


apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
name: prod-service
description: Cloud Run Prod service
run:
location: projects/secure-cicd-pipeline/locations/us-east1