steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args: ["--destination=$_AR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA", "--dockerfile=Dockerfile", "--cache=true", "--cache-ttl=24h"]    

timeout: '1600s'
