apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: v60-coffee
description: Workflow to deploy v60-coffee for the world
serialPipeline:
  stages:
  - targetId: beans
    profiles: [beans]
    strategy:
      standard:
        verify: false # incorporate verification from https://shell.cloud.google.com/?show=ide%2Cterminal&walkthrough_id=deploy--cloud-deploy-verification-run&pli=1
  - targetId: grind
    profiles: [grind]
    strategy:
      standard:
        verify: false
  - targetId: brew
    profiles: [brew]
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [25, 50, 75]
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: beans
description: v60 development environment on Cloud Run
run:
  location: projects/coffee-and-codey/locations/us-east1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: grind
description: v60 QA environment on Cloud Run
run:
  location: projects/coffee-and-codey/locations/us-east1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: brew-us
description: Depoy to production in US
run:
  location: projects/coffee-and-codey/locations/us-east1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: brew-europe
description: Depoy to production in Europe
run:
  location: projects/coffee-and-codey/locations/europe-west1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: brew
description: v60 PRODUCTION on Cloud Run
requireApproval: true
multiTarget:
  targetIds: [brew-us, brew-europe]
