apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: grind
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
      - name: app
        image: app
        env:
          - name: NAME
            value: "grind"