apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-coffee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-coffee
  template:
    metadata:
      labels:
        app: hello-coffee
    spec:
      containers:
        - name: hello-coffee
          image: europe-docker.pkg.dev/coffee-break-rob/coffee/hello-coffee:latest
