apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: coffee-break-rob
build:
  artifacts:
    - image: europe-docker.pkg.dev/coffee-break-rob/coffee/hello-coffee
      sync:
        infer:
          - '**/*.py'
  # local:
  #    push: true
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml