apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: v60-coffee
profiles:
- name: beans
  manifests:
    rawYaml:
    - deploy-beans.yaml
- name: grind
  manifests:
    rawYaml:
    - deploy-grind.yaml
- name: brew
  manifests:
    rawYaml:
    - deploy-brew.yaml
deploy:
  cloudrun: {}
verify:
  - name: verify-test
    container: 
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", 'echo "this is a verify action"' ]
      name: ubuntu
  - name: verify-endpoint-test
    container:
      name: gcloud
      image: gcr.io/cloud-builders/gcloud
      args: ["info"]  
customActions:
- name: predeploy-action
  containers:
  - name: predeploy-echo
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", 'echo "this is a predeploy action"' ]
  - name: slo-status
    image: gcr.io/google.com/cloudsdktool/cloud-sdk
    command: ["/bin/sh"]
    args: ["-c", 'result=$(curl -s -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" -X GET "https://monitoring.googleapis.com/v3/projects/coffee-and-codey/timeSeries?filter=select_slo_compliance(\"projects/300502296392/services/EdBHZ28PQQ6hnrzp_YTZeA/serviceLevelObjectives/lADl8mfLTUG64aE9yCnYEQ\")&interval.endTime=2024-03-28T11:05:00.0Z" | jq ".timeSeries[0].points[0].value.doubleValue") && [[ "$result" == "1" ]] && echo "SLO Compliance Check: PASS" || echo "SLO Compliance Check: FAIL"' ]
- name: postdeploy-action
  containers:
  - name: postdeploy-echo
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", 'echo "this is a postdeploy action"' ]