apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: v60-coffee
profiles:
- name: beans
  manifests:
    rawYaml:
    - deploy-beans.yaml
- name: grind
  manifests:
    rawYaml:
    - deploy-grind.yaml
- name: brew
  manifests:
    rawYaml:
    - deploy-brew.yaml
deploy:
  cloudrun: {}