apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: v60-coffee
profiles:
- name: beans
  manifests:
    rawYaml:
    - deploy-beans.yaml
- name: grind
  manifests:
    rawYaml:
    - deploy-grind.yaml
- name: brew
  manifests:
    rawYaml:
    - deploy-brew.yaml
deploy:
  cloudrun: {}
customActions:
- name: predeploy-action
  containers:
  - name: predeploy-echo
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", 'echo "this is a predeploy action"' ]
  - name: predeploy-echo2
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", 'echo "this is the 2nd predeploy action"' ]
- name: postdeploy-action
  containers:
  - name: postdeploy-echo
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", 'echo "this is a postdeploy action"' ]