steps:
# increase depth of git clone and diff
- id: 🗂️ Reset git to unshallow
  name: gcr.io/cloud-builders/git
  args:
    - fetch
    - '--unshallow'
- id: 🗂️ Pulling git history
  name: gcr.io/cloud-builders/git
  args:
    - pull
    - origin
    - $REF_NAME
- id: 🗂️ Comparing latest and most recent commits
  name: gcr.io/cloud-builders/git
  args:
    - diff
    - HEAD~1
    - '--output'
    - diff.txt

# ⁉️ Golang versions
- id: ⁉️ Golang Versions
  waitFor: ['-']
  name: "gcr.io/cloud-builders/go"
  args: ["version"]
  env: ["GOPATH=."]

# linter
- id: 👨‍💻 Linter
  waitFor: ['-']
  name: "golangci/golangci-lint"
  args: ["golangci-lint","run", "./ui/main.go"]

# unit Test
- id: 🧑‍🔬 Unit Test(s)
  waitFor: ['-']
  name: "gcr.io/cloud-builders/go"
  args: ["test","./ui/main_test.go"]
  env: ["GOPATH=."]

- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  id: "output the diff"
  entrypoint: /bin/bash
  args: 
    - -c
    - |
      cat diff.txt

- id: 🤖 Code review assistance
  name: 'europe-docker.pkg.dev/coffee-and-codey/buildey-image/buildey@sha256:c9d1a646bf282de0f036e05e43b6e15dadc64ec87f64645da3ba7a750c2423a9'
  args:
    - buildey
    - review
    - code
    - -f 
    - diff.txt
  allowFailure: true


### The below block should probably be in another workflow that is triggered once a mainal approval/review step is
# # Create Container Image
# - name: gcr.io/cloud-builders/docker
#   id: 🏗️ Build Container Image
#   args:
#     - build
#     - '-t'
#     - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE:$COMMIT_SHA'
#     - .

# # Push Container Image to Artifact Registry
# - name: gcr.io/cloud-builders/docker
#   id: 🏗️ Push Container Image
#   args:
#     - push
#     - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE:$COMMIT_SHA'

# # Get Image SHA from Artifact Registry
# ## Different format to `gcloud` builder example
# - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#   id: "🔐 Get Image Digest"
#   entrypoint: /bin/bash
#   args: 
#     - -c
#     - |
#       gcloud artifacts docker images describe \
#       $_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE:$COMMIT_SHA \
#       --format 'value(image_summary.digest)' > /workspace/image-sha.txt

# # Genereate SBOM
# - name: gcr.io/google.com/cloudsdktool/cloud-sdk
#   id: 🔐 Create a Software Bill of Materials (SBOM)
#   allowFailure: true
#   entrypoint: /bin/bash
#   args:
#     - -c
#     - |
#       gcloud artifacts sbom export --uri ${_AR_HOSTNAME}/${PROJECT_ID}/${_SERVICE_NAME}/${_IMAGE}@$(cat /workspace/image-sha.txt)
#     # - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE'

# images:
# - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME/$_IMAGE:$COMMIT_SHA'


options:
  # logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
  dynamicSubstitutions: true
